version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    user: "$USER_ID:$GROUP_ID"
    volumes:
      - './dist/backend/server:/app/backend'
      - './conf/config.toml:/app/config.toml'
    working_dir: /app
    command: "bash -c 'mkdir -p /tmp/data && /app/backend'"
    environment:
      ROCKET_ENV: production
      ROCKET_CONFIG: 'config.toml'
    networks: [default]

  nginx:
    image: nginx:1.18
    depends_on:
      - backend
    volumes:
      - './dist/frontend/:/var/www/html/:ro'
      - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports: [ '127.0.0.1:80:80' ]
    networks: [default]

  mailhog:
    image: mailhog/mailhog:v1.0.0
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:1080
      MH_UI_BIND_ADDR: 0.0.0.0:1080
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      TZ: Europe/Amsterdam
    ports: [ "127.0.0.1:1080:1080" ]
    networks: [default]
