[global]
server_url = "http://localhost"
address = "0.0.0.0"
data_dir = "/tmp/data"
email_from = "noreply@cryptify.local"
smtp_url = "mailhog"
smtp_port = 1025
# smtp_username = ""
# smtp_password = ""
irma_server = "http://localhost:8088"
