[global]
server_url = "https://cryptify.nl"
address = "0.0.0.0"
data_dir = "/tmp/data"
metadata_dir = "/tmp/metadata"
email_from = "noreply@cryptify.nl"
smtp_url = "mailhog"
smtp_port = 1025
# smtp_username = ""
# smtp_password = ""
