[global]
server_url = "https://postguard.nl/?download={uuid}#filesharing"
address = "0.0.0.0"
data_dir = "/tmp/data"
email_from = "noreply@postguard.nl"
# smtp_url = ""
# smtp_port = "" 
# smtp_credentials = ["user", "pw"]
irma_server = "http://irma:8088/"
allowed_origins = "^https://postguard.(eu|nl)$"
